export const studentList = [
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '0000',
    firstName: 'Ali',
    lastName: 'Haider',
    classValue: 7,
    enabled: true,
    id: 1,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '0001',
    firstName: 'Usman',
    lastName: 'Ali',
    classValue: 10,
    enabled: true,
    id: 2,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '0002',
    firstName: 'Sara',
    lastName: 'Queen',
    classValue: 12,
    enabled: true,
    id: 3,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '0003',
    firstName: 'Ash',
    lastName: 'Pearl',
    classValue: 12,
    enabled: true,
    id: 4,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '0004',
    firstName: 'Pol',
    lastName: 'Mark',
    classValue: 12,
    enabled: true,
    id: 5,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '0005',
    firstName: 'Umer',
    lastName: 'Man',
    classValue: 12,
    enabled: true,
    id: 6,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '0006',
    firstName: 'Sara',
    lastName: 'Ali',
    classValue: 12,
    enabled: true,
    id: 7,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '0007',
    firstName: 'Rania',
    lastName: 'Habibi',
    classValue: 12,
    enabled: true,
    id: 8,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '0008',
    firstName: 'Tareq',
    lastName: 'Sheikh',
    classValue: 12,
    enabled: true,
    id: 9,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '0009',
    firstName: 'Ali',
    lastName: 'Usman',
    classValue: 12,
    enabled: true,
    id: 10,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00010',
    firstName: 'Fahad',
    lastName: 'Hassan',
    classValue: 12,
    enabled: true,
    id: 11,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00011',
    firstName: 'Ali',
    lastName: 'Haider',
    classValue: 7,
    enabled: true,
    id: 12,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00012',
    firstName: 'Usman',
    lastName: 'Ali',
    classValue: 10,
    enabled: true,
    id: 13,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00013',
    firstName: 'Sara',
    lastName: 'Queen',
    classValue: 12,
    enabled: true,
    id: 14,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00014',
    firstName: 'Ash',
    lastName: 'Pearl',
    classValue: 12,
    enabled: true,
    id: 15,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00015',
    firstName: 'Pol',
    lastName: 'Mark',
    classValue: 12,
    enabled: true,
    id: 16,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00016',
    firstName: 'Umer',
    lastName: 'Man',
    classValue: 12,
    enabled: true,
    id: 17,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00017',
    firstName: 'Sara',
    lastName: 'Ali',
    classValue: 12,
    enabled: true,
    id: 18,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00018',
    firstName: 'Rania',
    lastName: 'Habibi',
    classValue: 12,
    enabled: true,
    id: 19,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00019',
    firstName: 'Tareq',
    lastName: 'Sheikh',
    classValue: 12,
    enabled: true,
    id: 20,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00020',
    firstName: 'Ali',
    lastName: 'Usman',
    classValue: 12,
    enabled: true,
    id: 21,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00021',
    firstName: 'Fahad',
    lastName: 'Hassan',
    classValue: 12,
    enabled: true,
    id: 22,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00022',
    firstName: 'Ali',
    lastName: 'Haider',
    classValue: 7,
    enabled: true,
    id: 23,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00023',
    firstName: 'Usman',
    lastName: 'Ali',
    classValue: 10,
    enabled: true,
    id: 24,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00024',
    firstName: 'Sara',
    lastName: 'Queen',
    classValue: 12,
    enabled: true,
    id: 25,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00025',
    firstName: 'Ash',
    lastName: 'Pearl',
    classValue: 12,
    enabled: true,
    id: 26,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00026',
    firstName: 'Pol',
    lastName: 'Mark',
    classValue: 12,
    enabled: true,
    id: 27,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00027',
    firstName: 'Umer',
    lastName: 'Man',
    classValue: 12,
    enabled: true,
    id: 28,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00028',
    firstName: 'Sara',
    lastName: 'Ali',
    classValue: 12,
    enabled: true,
    id: 29,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00029',
    firstName: 'Rania',
    lastName: 'Habibi',
    classValue: 12,
    enabled: true,
    id: 30,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00030',
    firstName: 'Tareq',
    lastName: 'Sheikh',
    classValue: 12,
    enabled: true,
    id: 31,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00031',
    firstName: 'Ali',
    lastName: 'Usman',
    classValue: 12,
    enabled: true,
    id: 32,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00032',
    firstName: 'Fahad',
    lastName: 'Hassan',
    classValue: 12,
    enabled: true,
    id: 33,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00033',
    firstName: 'Fahad',
    lastName: 'Hassan',
    classValue: 12,
    enabled: true,
    id: 34,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00034',
    firstName: 'Ali',
    lastName: 'Haider',
    classValue: 7,
    enabled: true,
    id: 35,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00035',
    firstName: 'Usman',
    lastName: 'Ali',
    classValue: 10,
    enabled: true,
    id: 36,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00036',
    firstName: 'Sara',
    lastName: 'Queen',
    classValue: 12,
    enabled: true,
    id: 37,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00037',
    firstName: 'Ash',
    lastName: 'Pearl',
    classValue: 12,
    enabled: true,
    id: 38,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00038',
    firstName: 'Pol',
    lastName: 'Mark',
    classValue: 12,
    enabled: true,
    id: 39,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00039',
    firstName: 'Umer',
    lastName: 'Man',
    classValue: 12,
    enabled: true,
    id: 40,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00040',
    firstName: 'Sara',
    lastName: 'Ali',
    classValue: 12,
    enabled: true,
    id: 41,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00041',
    firstName: 'Rania',
    lastName: 'Habibi',
    classValue: 12,
    enabled: true,
    id: 42,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00042',
    firstName: 'Tareq',
    lastName: 'Sheikh',
    classValue: 12,
    enabled: true,
    id: 43,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00043',
    firstName: 'Ali',
    lastName: 'Usman',
    classValue: 12,
    enabled: true,
    id: 44,
  },
  {
    picture: 'https://picsum.photos/200/300',
    rollNo: '00044',
    firstName: 'Fahad',
    lastName: 'Hassan',
    classValue: 12,
    enabled: true,
    id: 45,
  },
];

export const ADMIN_PROFILE = {
  name: 'Admin 1',
  id: '1001',
  type: 'Admin',
};

export const sampleMessages = [
  'I am good, how are you',
  'Sad to hear this',
  'You are going great job',
  'I was waiting for your messages',
  'Ahan, right',
  "That's cool",
  'What ? Can you please elaborate',
  'You are my hero',
  'Yes you are right',
  'Yes getting your point',
  'Done!',
];
